import { getDefaultConfig } from '@rainbow-me/rainbowkit';
import { 
  mainnet, 
  polygon, 
  arbitrum, 
  optimism, 
  base, 
  bsc, 
  avalanche, 
  fantom, 
  cronos,
  moonbeam,
  moonriver,
  harmonyOne,
  celo,
  gnosis,
  aurora,
  metis,
  polygonZkEvm,
  arbitrumNova
} from 'wagmi/chains';
import { http } from 'viem';

export const config = getDefaultConfig({
  appName: 'Portfolio Wallet DApp',
  projectId: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || 'your-project-id',
  chains: [
    mainnet, 
    polygon, 
    arbitrum, 
    optimism, 
    base, 
    bsc, 
    avalanche, 
    fantom, 
    cronos,
    moonbeam,
    moonriver,
    harmonyOne,
    celo,
    gnosis,
    aurora,
    metis,
    polygonZkEvm,
    arbitrumNova
  ],
  transports: {
    [mainnet.id]: http(process.env.NEXT_PUBLIC_ALCHEMY_ID ? `https://eth-mainnet.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_ID}` : undefined),
    [polygon.id]: http(process.env.NEXT_PUBLIC_ALCHEMY_ID ? `https://polygon-mainnet.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_ID}` : undefined),
    [arbitrum.id]: http(process.env.NEXT_PUBLIC_ALCHEMY_ID ? `https://arb-mainnet.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_ID}` : undefined),
    [optimism.id]: http(process.env.NEXT_PUBLIC_ALCHEMY_ID ? `https://opt-mainnet.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_ID}` : undefined),
    [base.id]: http(process.env.NEXT_PUBLIC_ALCHEMY_ID ? `https://base-mainnet.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_ID}` : undefined),
    [bsc.id]: http('https://bsc-dataseed.binance.org/'),
    [avalanche.id]: http('https://api.avax.network/ext/bc/C/rpc'),
    [fantom.id]: http('https://rpc.ftm.tools/'),
    [cronos.id]: http('https://evm.cronos.org'),
    [moonbeam.id]: http('https://rpc.api.moonbeam.network'),
    [moonriver.id]: http('https://rpc.api.moonriver.moonbeam.network'),
    [harmonyOne.id]: http('https://api.harmony.one'),
    [celo.id]: http('https://forno.celo.org'),
    [gnosis.id]: http('https://rpc.gnosischain.com'),
    [aurora.id]: http('https://mainnet.aurora.dev'),
    [metis.id]: http('https://andromeda.metis.io/?owner=1088'),
    [polygonZkEvm.id]: http('https://zkevm-rpc.com'),
    [arbitrumNova.id]: http('https://nova.arbitrum.io/rpc'),
  },
  ssr: true,
});
